In [1]:
import requests

In [2]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"
standings_url2 = "https://fbref.com/en/comps/11/Serie-A-Stats"

In [3]:
data = requests.get(standings_url2)

In [4]:
from bs4 import BeautifulSoup
import time

In [5]:
soup = BeautifulSoup(data.text)
time.sleep(5)
soup
standings_table = soup.select('table.stats_table')[0]
links = standings_table.find_all('a')
links = [l.get("href") for l in links]
links = [l for l in links if '/squads/' in l]

IndexError: list index out of range

In [51]:
team_urls = [f"https://fbref.com{l}" for l in links]

In [52]:
data = requests.get(team_urls[0])

In [53]:
import pandas as pd
matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/4209044294.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

ValueError: No tables found

In [32]:
soup = BeautifulSoup(data.text)
links = soup.find_all('a')
links = [l.get("href") for l in links]
links = [l for l in links if l and 'all_comps/shooting/' in l]

In [33]:
data = requests.get(f"https://fbref.com{links[0]}")

In [34]:
shooting = pd.read_html(data.text, match="Shooting")[0]

/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2517714723.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]

In [37]:
shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2024-08-10,21:15,Coppa Italia,First round,Sat,Home,D,0 (4),0 (3),Modena,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Match Report
1,2024-08-18,18:30,Serie A,Matchweek 1,Sun,Away,L,0,3,Hellas Verona,...,17.8,0.0,0,0,1.0,1.0,0.07,-1.0,-1.0,Match Report
2,2024-08-25,20:45,Serie A,Matchweek 2,Sun,Home,W,3,0,Bologna,...,17.5,0.0,0,0,2.5,2.5,0.15,0.5,0.5,Match Report
3,2024-08-31,20:45,Serie A,Matchweek 3,Sat,Home,W,2,1,Parma,...,17.5,1.0,0,0,2.2,2.2,0.08,-0.2,-0.2,Match Report
4,2024-09-15,18:00,Serie A,Matchweek 4,Sun,Away,W,4,0,Cagliari,...,16.0,0.0,0,0,1.9,1.9,0.15,2.1,2.1,Match Report

In [36]:
shooting.columns = shooting.columns.droplevel()

In [38]:
team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")

In [40]:
years = list(range(2024, 2022, -1))
all_matches = []

In [41]:
import time
for year in years:
    data = requests.get(standings_url2)
    soup = BeautifulSoup(data.text)
    standings_table = soup.select('table.stats_table')[0]

    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]
    
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url2 = f"https://fbref.com{previous_season}"
    
    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all('a')]
        links = [l for l in links if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
        except ValueError:
            continue
        team_data = team_data[team_data["Comp"] == "Serie A"]
        
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)
        time.sleep(1)

/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
/var/folders/8h/b6sjd9l522v8k4p6t77m8fpm0000gn/T/ipykernel_9861/2166766338.py:22: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  shooting = pd.read_html(data.text, match="Shooting")[0]

ValueError: No tables found

In [43]:
all_matches

[         Date   Time     Comp        Round  Day Venue Result GF GA  \
 1  2024-08-18  18:30  Serie A  Matchweek 1  Sun  Away      L  0  3
 2  2024-08-25  20:45  Serie A  Matchweek 2  Sun  Home      W  3  0
 3  2024-08-31  20:45  Serie A  Matchweek 3  Sat  Home      W  2  1
 4  2024-09-15  18:00  Serie A  Matchweek 4  Sun  Away      W  4  0
 5  2024-09-21  18:00  Serie A  Matchweek 5  Sat  Away      D  0  0
 7  2024-09-29  20:45  Serie A  Matchweek 6  Sun  Home      W  2  0
 8  2024-10-04  18:30  Serie A  Matchweek 7  Fri  Home      W  3  1

         Opponent  ...  Match Report  Notes  Sh  SoT  Dist   FK PK PKatt  \
 1  Hellas Verona  ...  Match Report    NaN  14    4  17.8  0.0  0     0
 2        Bologna  ...  Match Report    NaN  16    5  17.5  0.0  0     0
 3          Parma  ...  Match Report    NaN  29    7  17.5  1.0  0     0
 4       Cagliari  ...  Match Report    NaN  13    5  16.0  0.0  0     0
 5       Juventus  ...  Match Report    NaN   8    1  23.4  0.0  0     0
 7          Monza  ...  Match Report    NaN  11    2  13.8  0.0  0     0
 8           Como  ...  Match Report    NaN   8    5  18.1  0.0  1     1

   Season    Team
 1   2022  Napoli
 2   2022  Napoli
 3   2022  Napoli
 4   2022  Napoli
 5   2022  Napoli
 7   2022  Napoli
 8   2022  Napoli

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 0  2024-08-17  18:30  Serie A  Matchweek 1  Sat  Away      D  2.0  2.0
 1  2024-08-24  20:45  Serie A  Matchweek 2  Sat  Home      W  2.0  0.0
 2  2024-08-30  20:45  Serie A  Matchweek 3  Fri  Home      W  4.0  0.0
 3  2024-09-15  20:45  Serie A  Matchweek 4  Sun  Away      D  1.0  1.0
 5  2024-09-22  20:45  Serie A  Matchweek 5  Sun  Home      L  1.0  2.0
 6  2024-09-28  15:00  Serie A  Matchweek 6  Sat  Away      W  3.0  2.0
 8  2024-10-05  20:45  Serie A  Matchweek 7  Sat  Home      W  3.0  2.0

    Opponent  ...  Match Report  Notes  Sh  SoT  Dist FK PK PKatt Season  \
 0     Genoa  ...  Match Report    NaN  17    7  13.7  1  0     0   2022
 1     Lecce  ...  Match Report    NaN  10    2  15.2  1  1     1   2022
 2  Atalanta  ...  Match Report    NaN  13    4  17.9  0  0     0   2022
 3     Monza  ...  Match Report    NaN  16    2  14.8  0  0     0   2022
 5     Milan  ...  Match Report    NaN  13    4  17.7  0  0     0   2022
 6   Udinese  ...  Match Report    NaN  16    7  14.7  0  0     0   2022
 8    Torino  ...  Match Report    NaN  29    8  18.7  0  0     0   2022

              Team
 0  Internazionale
 1  Internazionale
 2  Internazionale
 3  Internazionale
 5  Internazionale
 6  Internazionale
 8  Internazionale

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 0  2024-08-19  20:45  Serie A  Matchweek 1  Mon  Home      W  3.0  0.0
 1  2024-08-26  20:45  Serie A  Matchweek 2  Mon  Away      W  3.0  0.0
 2  2024-09-01  20:45  Serie A  Matchweek 3  Sun  Home      D  0.0  0.0
 3  2024-09-14  18:00  Serie A  Matchweek 4  Sat  Away      D  0.0  0.0
 5  2024-09-21  18:00  Serie A  Matchweek 5  Sat  Home      D  0.0  0.0
 6  2024-09-28  18:00  Serie A  Matchweek 6  Sat  Away      W  3.0  0.0
 8  2024-10-06  12:30  Serie A  Matchweek 7  Sun  Home      D  1.0  1.0

         Opponent  ...  Match Report  Notes  Sh  SoT  Dist FK PK PKatt Season  \
 0           Como  ...  Match Report    NaN  13    6  20.0  1  0     0   2022
 1  Hellas Verona  ...  Match Report    NaN   7    4  18.4  0  1     1   2022
 2           Roma  ...  Match Report    NaN   8    1  16.5  1  0     0   2022
 3         Empoli  ...  Match Report    NaN  15    3  18.7  0  0     0   2022
 5         Napoli  ...  Match Report    NaN   9    1  20.4  0  0     0   2022
 6          Genoa  ...  Match Report    NaN  11    2  16.9  1  1     1   2022
 8       Cagliari  ...  Match Report    NaN  20    8  16.6  0  1     1   2022

        Team
 0  Juventus
 1  Juventus
 2  Juventus
 3  Juventus
 5  Juventus
 6  Juventus
 8  Juventus

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 0  2024-08-18  20:45  Serie A  Matchweek 1  Sun  Home      W  3.0  1.0
 1  2024-08-24  18:30  Serie A  Matchweek 2  Sat  Away      L  1.0  2.0
 2  2024-08-31  20:45  Serie A  Matchweek 3  Sat  Home      D  2.0  2.0
 3  2024-09-16  20:45  Serie A  Matchweek 4  Mon  Home      W  2.0  1.0
 4  2024-09-22  12:30  Serie A  Matchweek 5  Sun  Away      L  1.0  2.0
 6  2024-09-29  12:30  Serie A  Matchweek 6  Sun  Away      W  3.0  2.0
 8  2024-10-06  15:00  Serie A  Matchweek 7  Sun  Home      W  2.0  1.0

         Opponent  ...  Match Report  Notes  Sh  SoT  Dist FK PK PKatt Season  \
 0        Venezia  ...  Match Report    NaN  12    5  16.7  0  1     1   2022
 1        Udinese  ...  Match Report    NaN  17    4  15.6  0  0     0   2022
 2          Milan  ...  Match Report    NaN   7    4   9.3  0  0     0   2022
 3  Hellas Verona  ...  Match Report    NaN  14    7  21.9  0  0     0   2022
 4     Fiorentina  ...  Match Report    NaN  20    6  19.5  1  0     0   2022
 6         Torino  ...  Match Report    NaN  13    7  15.6  0  0     0   2022
 8         Empoli  ...  Match Report    NaN  15    5  18.6  0  0     1   2022

     Team
 0  Lazio
 1  Lazio
 2  Lazio
 3  Lazio
 4  Lazio
 6  Lazio
 8  Lazio

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 1  2024-08-18  18:30  Serie A  Matchweek 1  Sun  Away      D  1.0  1.0
 2  2024-08-24  18:30  Serie A  Matchweek 2  Sat  Home      W  2.0  1.0
 3  2024-09-01  20:45  Serie A  Matchweek 3  Sun  Home      W  1.0  0.0
 4  2024-09-16  18:30  Serie A  Matchweek 4  Mon  Away      W  3.0  2.0
 5  2024-09-22  18:00  Serie A  Matchweek 5  Sun  Away      L  0.0  3.0
 7  2024-09-28  15:00  Serie A  Matchweek 6  Sat  Home      L  2.0  3.0
 8  2024-10-05  15:00  Serie A  Matchweek 7  Sat  Home      W  1.0  0.0

   Opponent  ...  Match Report  Notes  Sh  SoT  Dist   FK PK PKatt Season  \
 1  Bologna  ...  Match Report    NaN   3    1  17.7  0.0  0     1   2022
 2    Lazio  ...  Match Report    NaN   8    3  19.4  0.0  0     0   2022
 3     Como  ...  Match Report    NaN  10    2  14.6  0.0  0     0   2022
 4    Parma  ...  Match Report    NaN  18    6  15.1  0.0  0     0   2022
 5     Roma  ...  Match Report    NaN   9    2  17.6  0.0  0     0   2022
 7    Inter  ...  Match Report    NaN   9    3  14.4  0.0  0     0   2022
 8    Lecce  ...  Match Report    NaN  12    4  12.8  1.0  0     0   2022

       Team
 1  Udinese
 2  Udinese
 3  Udinese
 4  Udinese
 5  Udinese
 7  Udinese
 8  Udinese

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 0  2024-08-17  20:45  Serie A  Matchweek 1  Sat  Home      D  2.0  2.0
 1  2024-08-24  18:30  Serie A  Matchweek 2  Sat  Away      L  1.0  2.0
 2  2024-08-31  20:45  Serie A  Matchweek 3  Sat  Away      D  2.0  2.0
 3  2024-09-14  20:45  Serie A  Matchweek 4  Sat  Home      W  4.0  0.0
 5  2024-09-22  20:45  Serie A  Matchweek 5  Sun  Away      W  2.0  1.0
 6  2024-09-27  20:45  Serie A  Matchweek 6  Fri  Home      W  3.0  0.0
 8  2024-10-06  20:45  Serie A  Matchweek 7  Sun  Away      L  1.0  2.0

      Opponent  ...  Match Report  Notes  Sh  SoT  Dist FK PK PKatt Season  \
 0      Torino  ...  Match Report    NaN  26    5  18.5  0  0     0   2022
 1       Parma  ...  Match Report    NaN  17    5  18.6  0  0     0   2022
 2       Lazio  ...  Match Report    NaN  10    4  17.5  1  0     0   2022
 3     Venezia  ...  Match Report    NaN  10    6  20.0  0  2     2   2022
 5       Inter  ...  Match Report    NaN  16    8  16.4  0  0     0   2022
 6       Lecce  ...  Match Report    NaN  15    6  16.4  0  0     0   2022
 8  Fiorentina  ...  Match Report    NaN  14    6  17.0  0  0     2   2022

     Team
 0  Milan
 1  Milan
 2  Milan
 3  Milan
 5  Milan
 6  Milan
 8  Milan

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 1  2024-08-17  20:45  Serie A  Matchweek 1  Sat  Away      D  2.0  2.0
 2  2024-08-25  18:30  Serie A  Matchweek 2  Sun  Home      W  2.0  1.0
 3  2024-08-30  18:30  Serie A  Matchweek 3  Fri  Away      W  1.0  0.0
 4  2024-09-15  15:00  Serie A  Matchweek 4  Sun  Home      D  0.0  0.0
 5  2024-09-20  20:45  Serie A  Matchweek 5  Fri  Away      W  3.0  2.0
 7  2024-09-29  12:30  Serie A  Matchweek 6  Sun  Home      L  2.0  3.0
 8  2024-10-05  20:45  Serie A  Matchweek 7  Sat  Away      L  2.0  3.0

         Opponent  ...  Match Report  Notes  Sh  SoT  Dist   FK PK PKatt  \
 1          Milan  ...  Match Report    NaN   7    3  16.3  0.0  0     0
 2       Atalanta  ...  Match Report    NaN  13    6  15.5  1.0  0     0
 3        Venezia  ...  Match Report    NaN  12    5  17.0  0.0  0     0
 4          Lecce  ...  Match Report    NaN   5    0  17.4  1.0  0     0
 5  Hellas Verona  ...  Match Report    NaN  15    3  18.9  1.0  0     1
 7          Lazio  ...  Match Report    NaN  12    7  19.5  1.0  0     0
 8          Inter  ...  Match Report    NaN   6    4  21.8  0.0  1     1

   Season    Team
 1   2022  Torino
 2   2022  Torino
 3   2022  Torino
 4   2022  Torino
 5   2022  Torino
 7   2022  Torino
 8   2022  Torino

 [7 rows x 28 columns],
          Date   Time     Comp        Round  Day Venue Result   GF   GA  \
 1  2024-08-19  18:30  Serie A  Matchweek 1  Mon  Away      W  4.0  0.0
 2  2024-08-25  18:30  Serie A  Matchweek 2  Sun  Away      L  1.0  2.0
 3  2024-08-30  20:45  Serie A  Matchweek 3  Fri  Away      L  0.0  4.0
 4  2024-09-15  15:00  Serie A  Matchweek 4  Sun  Home      W  3.0  2.0
 6  2024-09-24  20:45  Serie A  Matchweek 5  Tue  Home      L  2.0  3.0
 7  2024-09-28  20:45  Serie A  Matchweek 6  Sat  Away      D  1.0  1.0
 9  2024-10-05  18:00  Serie A  Matchweek 7  Sat  Home      W  5.0  1.0

      Opponent  ...  Match Report  Notes  Sh  SoT  Dist   FK PK PKatt Season  \
 1       Lecce  ...  Match Report    NaN  10    5  13.4  0.0  1     1   2022
 2      Torino  ...  Match Report    NaN  24    8  16.0  1.0  0     1   2022
 3       Inter  ...  Match Report    NaN  11    1  17.1  0.0  0     0   2022
 4  Fiorentina  ...  Match Report    NaN  13    7  13.6  0.0  0     0   2022
 6        Como  ...  Match Report    NaN   7    4  20.0  0.0  1     1   2022
 7     Bologna  ...  Match Report    NaN  23    4  16.2  0.0  0     0   2022
 9       Genoa  ...  Match Report    NaN  22    7  15.3  0.0  1     1   2022

        Team
 1  Atalanta
 2  Atalanta
 3  Atalanta
 4  Atalanta
 6  Atalanta
 7  Atalanta
 9  Atalanta

 [7 rows x 28 columns]]

In [44]:
match_df = pd.concat(all_matches)
match_df.columns = [c.lower() for c in match_df.columns]
match_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2024-08-18,18:30,Serie A,Matchweek 1,Sun,Away,L,0,3,Hellas Verona,...,Match Report,NaN,14,4,17.8,0.0,0,0,2022,Napoli
2,2024-08-25,20:45,Serie A,Matchweek 2,Sun,Home,W,3,0,Bologna,...,Match Report,NaN,16,5,17.5,0.0,0,0,2022,Napoli
3,2024-08-31,20:45,Serie A,Matchweek 3,Sat,Home,W,2,1,Parma,...,Match Report,NaN,29,7,17.5,1.0,0,0,2022,Napoli
4,2024-09-15,18:00,Serie A,Matchweek 4,Sun,Away,W,4,0,Cagliari,...,Match Report,NaN,13,5,16.0,0.0,0,0,2022,Napoli
5,2024-09-21,18:00,Serie A,Matchweek 5,Sat,Away,D,0,0,Juventus,...,Match Report,NaN,8,1,23.4,0.0,0,0,2022,Napoli
7,2024-09-29,20:45,Serie A,Matchweek 6,Sun,Home,W,2,0,Monza,...,Match Report,NaN,11,2,13.8,0.0,0,0,2022,Napoli
8,2024-10-04,18:30,Serie A,Matchweek 7,Fri,Home,W,3,1,Como,...,Match Report,NaN,8,5,18.1,0.0,1,1,2022,Napoli
0,2024-08-17,18:30,Serie A,Matchweek 1,Sat,Away,D,2.0,2.0,Genoa,...,Match Report,NaN,17,7,13.7,1.0,0,0,2022,Internazionale
1,2024-08-24,20:45,Serie A,Matchweek 2,Sat,Home,W,2.0,0.0,Lecce,...,Match Report,NaN,10,2,15.2,1.0,1,1,2022,Internazionale
2,2024-08-30,20:45,Serie A,Matchweek 3,Fri,Home,W,4.0,0.0,Atalanta,...,Match Report,NaN,13,4,17.9,0.0,0,0,2022,Internazionale
3,2024-09-15,20:45,Serie A,Matchweek 4,Sun,Away,D,1.0,1.0,Monza,...,Match Report,NaN,16,2,14.8,0.0,0,0,2022,Internazionale
5,2024-09-22,20:45,Serie A,Matchweek 5,Sun,Home,L,1.0,2.0,Milan,...,Match Report,NaN,13,4,17.7,0.0,0,0,2022,Internazionale
6,2024-09-28,15:00,Serie A,Matchweek 6,Sat,Away,W,3.0,2.0,Udinese,...,Match Report,NaN,16,7,14.7,0.0,0,0,2022,Internazionale
8,2024-10-05,20:45,Serie A,Matchweek 7,Sat,Home,W,3.0,2.0,Torino,...,Match Report,NaN,29,8,18.7,0.0,0,0,2022,Internazionale
0,2024-08-19,20:45,Serie A,Matchweek 1,Mon,Home,W,3.0,0.0,Como,...,Match Report,NaN,13,6,20.0,1.0,0,0,2022,Juventus
1,2024-08-26,20:45,Serie A,Matchweek 2,Mon,Away,W,3.0,0.0,Hellas Verona,...,Match Report,NaN,7,4,18.4,0.0,1,1,2022,Juventus
2,2024-09-01,20:45,Serie A,Matchweek 3,Sun,Home,D,0.0,0.0,Roma,...,Match Report,NaN,8,1,16.5,1.0,0,0,2022,Juventus
3,2024-09-14,18:00,Serie A,Matchweek 4,Sat,Away,D,0.0,0.0,Empoli,...,Match Report,NaN,15,3,18.7,0.0,0,0,2022,Juventus
5,2024-09-21,18:00,Serie A,Matchweek 5,Sat,Home,D,0.0,0.0,Napoli,...,Match Report,NaN,9,1,20.4,0.0,0,0,2022,Juventus
6,2024-09-28,18:00,Serie A,Matchweek 6,Sat,Away,W,3.0,0.0,Genoa,...,Match Report,NaN,11,2,16.9,1.0,1,1,2022,Juventus
8,2024-10-06,12:30,Serie A,Matchweek 7,Sun,Home,D,1.0,1.0,Cagliari,...,Match Report,NaN,20,8,16.6,0.0,1,1,2022,Juventus
0,2024-08-18,20:45,Serie A,Matchweek 1,Sun,Home,W,3.0,1.0,Venezia,...,Match Report,NaN,12,5,16.7,0.0,1,1,2022,Lazio
1,2024-08-24,18:30,Serie A,Matchweek 2,Sat,Away,L,1.0,2.0,Udinese,...,Match Report,NaN,17,4,15.6,0.0,0,0,2022,Lazio
2,2024-08-31,20:45,Serie A,Matchweek 3,Sat,Home,D,2.0,2.0,Milan,...,Match Report,NaN,7,4,9.3,0.0,0,0,2022,Lazio
3,2024-09-16,20:45,Serie A,Matchweek 4,Mon,Home,W,2.0,1.0,Hellas Verona,...,Match Report,NaN,14,7,21.9,0.0,0,0,2022,Lazio
4,2024-09-22,12:30,Serie A,Matchweek 5,Sun,Away,L,1.0,2.0,Fiorentina,...,Match Report,NaN,20,6,19.5,1.0,0,0,2022,Lazio
6,2024-09-29,12:30,Serie A,Matchweek 6,Sun,Away,W,3.0,2.0,Torino,...,Match Report,NaN,13,7,15.6,0.0,0,0,2022,Lazio
8,2024-10-06,15:00,Serie A,Matchweek 7,Sun,Home,W,2.0,1.0,Empoli,...,Match Report,NaN,15,5,18.6,0.0,0,1,2022,Lazio
1,2024-08-18,18:30,Serie A,Matchweek 1,Sun,Away,D,1.0,1.0,Bologna,...,Match Report,NaN,3,1,17.7,0.0,0,1,2022,Udinese
2,2024-08-24,18:30,Serie A,Matchweek 2,Sat,Home,W,2.0,1.0,Lazio,...,Match Report,NaN,8,3,19.4,0.0,0,0,2022,Udinese
3,2024-09-01,20:45,Serie A,Matchweek 3,Sun,Home,W,1.0,0.0,Como,...,Match Report,NaN,10,2,14.6,0.0,0,0,2022,Udinese
4,2024-09-16,18:30,Serie A,Matchweek 4,Mon,Away,W,3.0,2.0,Parma,...,Match Report,NaN,18,6,15.1,0.0,0,0,2022,Udinese
5,2024-09-22,18:00,Serie A,Matchweek 5,Sun,Away,L,0.0,3.0,Roma,...,Match Report,NaN,9,2,17.6,0.0,0,0,2022,Udinese
7,2024-09-28,15:00,Serie A,Matchweek 6,Sat,Home,L,2.0,3.0,Inter,...,Match Report,NaN,9,3,14.4,0.0,0,0,2022,Udinese
8,2024-10-05,15:00,Serie A,Matchweek 7,Sat,Home,W,1.0,0.0,Lecce,...,Match Report,NaN,12,4,12.8,1.0,0,0,2022,Udinese
0,2024-08-17,20:45,Serie A,Matchweek 1,Sat,Home,D,2.0,2.0,Torino,...,Match Report,NaN,26,5,18.5,0.0,0,0,2022,Milan
1,2024-08-24,18:30,Serie A,Matchweek 2,Sat,Away,L,1.0,2.0,Parma,...,Match Report,NaN,17,5,18.6,0.0,0,0,2022,Milan
2,2024-08-31,20:45,Serie A,Matchweek 3,Sat,Away,D,2.0,2.0,Lazio,...,Match Report,NaN,10,4,17.5,1.0,0,0,2022,Milan
3,2024-09-14,20:45,Serie A,Matchweek 4,Sat,Home,W,4.0,0.0,Venezia,...,Match Report,NaN,10,6,20.0,0.0,2,2,2022,Milan
5,2024-09-22,20:45,Serie A,Matchweek 5,Sun,Away,W,2.0,1.0,Inter,...,Match Report,NaN,16,8,16.4,0.0,0,0,2022,Milan
6,2024-09-27,20:45,Serie A,Matchweek 6,Fri,Home,W,3.0,0.0,Lecce,...,Match Report,NaN,15,6,16.4,0.0,0,0,2022,Milan
8,2024-10-06,20:45,Serie A,Matchweek 7,Sun,Away,L,1.0,2.0,Fiorentina,...,Match Report,NaN,14,6,17.0,0.0,0,2,2022,Milan
1,2024-08-17,20:45,Serie A,Matchweek 1,Sat,Away,D,2.0,2.0,Milan,...,Match Report,NaN,7,3,16.3,0.0,0,0,2022,Torino
2,2024-08-25,18:30,Serie A,Matchweek 2,Sun,Home,W,2.0,1.0,Atalanta,...,Match Report,NaN,13,6,15.5,1.0,0,0,2022,Torino
3,2024-08-30,18:30,Serie A,Matchweek 3,Fri,Away,W,1.0,0.0,Venezia,...,Match Report,NaN,12,5,17.0,0.0,0,0,2022,Torino
4,2024-09-15,15:00,Serie A,Matchweek 4,Sun,Home,D,0.0,0.0,Lecce,...,Match Report,NaN,5,0,17.4,1.0,0,0,2022,Torino
5,2024-09-20,20:45,Serie A,Matchweek 5,Fri,Away,W,3.0,2.0,Hellas Verona,...,Match Report,NaN,15,3,18.9,1.0,0,1,2022,Torino
7,2024-09-29,12:30,Serie A,Matchweek 6,Sun,Home,L,2.0,3.0,Lazio,...,Match Report,NaN,12,7,19.5,1.0,0,0,2022,Torino
8,2024-10-05,20:45,Serie A,Matchweek 7,Sat,Away,L,2.0,3.0,Inter,...,Match Report,NaN,6,4,21.8,0.0,1,1,2022,Torino
1,2024-08-19,18:30,Serie A,Matchweek 1,Mon,Away,W,4.0,0.0,Lecce,...,Match Report,NaN,10,5,13.4,0.0,1,1,2022,Atalanta
2,2024-08-25,18:30,Serie A,Matchweek 2,Sun,Away,L,1.0,2.0,Torino,...,Match Report,NaN,24,8,16.0,1.0,0,1,2022,Atalanta
3,2024-08-30,20:45,Serie A,Matchweek 3,Fri,Away,L,0.0,4.0,Inter,...,Match Report,NaN,11,1,17.1,0.0,0,0,2022,Atalanta
4,2024-09-15,15:00,Serie A,Matchweek 4,Sun,Home,W,3.0,2.0,Fiorentina,...,Match Report,NaN,13,7,13.6,0.0,0,0,2022,Atalanta
6,2024-09-24,20:45,Serie A,Matchweek 5,Tue,Home,L,2.0,3.0,Como,...,Match Report,NaN,7,4,20.0,0.0,1,1,2022,Atalanta
7,2024-09-28,20:45,Serie A,Matchweek 6,Sat,Away,D,1.0,1.0,Bologna,...,Match Report,NaN,23,4,16.2,0.0,0,0,2022,Atalanta
9,2024-10-05,18:00,Serie A,Matchweek 7,Sat,Home,W,5.0,1.0,Genoa,...,Match Report,NaN,22,7,15.3,0.0,1,1,2022,Atalanta

In [45]:
match_df.to_csv("matches.csv")